
---
name: Tests

on: push

concurrency: 
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: tests

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.9']
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - uses: azure/setup-helm@v3
      with:
        version: 'latest'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Kind
      run: |
        if ! kind --version
        then
          mkdir .bin
          ARCH=linux-amd64
          [[ ${{ matrix.os }} == "macos-"*  ]] && ARCH=darwin-amd64
          kind_latest_version=$(curl --silent "https://api.github.com/repos/kubernetes-sigs/kind/releases/latest" | jq -r .tag_name)
          curl -Lo .bin/kind https://kind.sigs.k8s.io/dl/$kind_latest_version/kind-${ARCH}
          chmod +x .bin/kind
        fi
        echo "$GITHUB_WORKSPACE/.bin" >> $GITHUB_PATH

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - uses: docker-practice/actions-setup-docker@master
      if: ${{ startsWith( matrix.os, 'macos' ) }}

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Start Playground
      run: |
        python -u kindplay/cli.py start tests/playgrounds/basic/